CREATE TABLE [dbo].[TasksInTags] (
    [TaskId]    INT NOT NULL,
    [TagId] INT NOT NULL,
    CONSTRAINT [PK_TasksInTags] PRIMARY KEY CLUSTERED ([TaskId] ASC, [TagId] ASC),
    CONSTRAINT [FK_TasksInTags_Tasks] FOREIGN KEY ([TaskId]) REFERENCES [dbo].[Tasks] ([TaskId]) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT [FK_TasksInTags_Tags] FOREIGN KEY ([TagId]) REFERENCES [dbo].[Tags] ([TagId]) ON DELETE CASCADE ON UPDATE CASCADE
);

